#ifndef __ZEPHYRPROJECT_ZEPHYR_PROJECTS_PLANTMONITOR_SRC_SENSORS_DHT11_H_
#define __ZEPHYRPROJECT_ZEPHYR_PROJECTS_PLANTMONITOR_SRC_SENSORS_DHT11_H_

#include <zephyr/device.h>
#include <zephyr/drivers/sensor.h>

void ThreadDHT11(void);

#endif // __ZEPHYRPROJECT_ZEPHYR_PROJECTS_PLANTMONITOR_SRC_SENSORS_DHT11_H_