#ifndef __ZEPHYRPROJECT_ZEPHYR_PROJECTS_PLANTMONITOR_SRC_DATATYPES_H_
#define __ZEPHYRPROJECT_ZEPHYR_PROJECTS_PLANTMONITOR_SRC_DATATYPES_H_

#include <stdio.h>

struct data_item_type {
    uint8_t data;
	uint8_t id;
};

#endif // __ZEPHYRPROJECT_ZEPHYR_PROJECTS_PLANTMONITOR_SRC_DATATYPES_H_